version: '3.8'
services:
    app:
        build: .
        ports:
            - 5000:5000
        env_file: .env
        depends_on:
            - db
        container_name: chat_ts
    db:
        image: postgres:14.4
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: superpass
            POSTGRES_DB: chat_db
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./sql/:/docker-entrypoint-initdb.d
        container_name: chat_postgres
volumes:
    db-data:
