version: '3.8'
services:
    app:
        build: .
        ports:
            - 5000:5000
        env_file: .env
        environment:
            DB_HOST: chat_postgres
        depends_on:
            - db
        container_name: chat_ts
        networks:
            - local
    db:
        image: postgres:14.4
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: superpass
            POSTGRES_DB: chat_db
        ports:
            - 5432:5432
        volumes:
            - db-data:/tmp/chat
            - ./sql/:/docker-entrypoint-initdb.d
        container_name: chat_postgres
        networks:
            - local
volumes:
    db-data:
networks:
    local:
        driver: bridge
